const OP_CONNECTION = "CONNECTION";
const OP_INPUT = "INPUT";
const OP_COMPILE = "COMPILE";
const OP_LAUNCH_DEBUGGER = "DEBUGGER_LAUNCH";
const OP_TEST = "TEST";
const OP_PING = "PING";

const SENDER_HOST = "HOST_SERVER";
const SENDER_USER = "USER_SENDER";
const SENDER_DEBUGGER = "DEBUGGER_SENDER";

const ENV_REFRESH = 0;
const ENV_FAIL = 1;
const ENV_LAUNCHING = 2;
const ENV_SUCCESS = 3;

export {OP_CONNECTION, OP_INPUT, OP_LAUNCH_DEBUGGER, SENDER_HOST, SENDER_USER, SENDER_DEBUGGER, OP_COMPILE, OP_TEST, ENV_FAIL, ENV_LAUNCHING, ENV_REFRESH, ENV_SUCCESS, OP_PING}