const OP_CONNECTION = "CONNECTION";
const OP_INPUT = "INPUT";
const OP_COMPILE = "COMPILE";
const OP_LAUNCH_DEBUGGER = "DEBUGGER_LAUNCH";
const OP_TEST = "TEST";
const OP_PING = "PING";
const OP_MOVE_ACTIVE_SESSION = 5;

const EVENT_ON_BREAK = 0;
const EVENT_ON_STDOUT = 1;
const EVENT_ON_COMPILE_SUCCESS = 2;
const EVENT_ON_COMPILE_FAILURE = 3;

const SENDER_HOST = "HOST_SERVER";
const SENDER_USER = "USER_SENDER";
const SENDER_DEBUGGER = "DEBUGGER_SENDER";

const ENV_REFRESH = 0;
const ENV_FAIL = 1;
const ENV_LAUNCHING = 2;
const ENV_SUCCESS = 3;
const ENV_MULTIPLE_ERROR = 4;

export {OP_CONNECTION, OP_INPUT, OP_LAUNCH_DEBUGGER, SENDER_HOST, SENDER_USER, SENDER_DEBUGGER, OP_COMPILE, OP_TEST, ENV_FAIL, ENV_LAUNCHING, ENV_REFRESH, ENV_SUCCESS, OP_PING, ENV_MULTIPLE_ERROR,
        OP_MOVE_ACTIVE_SESSION, EVENT_ON_BREAK, EVENT_ON_STDOUT, EVENT_ON_COMPILE_FAILURE, EVENT_ON_COMPILE_SUCCESS}