
const OP_INPUT = "INPUT";
const OP_COMPILE = "COMPILE";
const OP_TEST = "TEST";

const EVENT_ONBREAK = 0;
const EVENT_ONSTDOUT = 1;
const EVENT_ONCOMPILE_SUCCESS = 2;
const EVENT_ONCOMPILE_FAILURE = 3;
const EVENT_ONPROGRAM_EXIT = 4;

const SENDER_HOST = "HOST_SERVER";
const SENDER_USER = "USER_SENDER";
const SENDER_DEBUGGER = "DEBUGGER_SENDER";

export {OP_COMPILE, OP_INPUT, OP_TEST,
        EVENT_ONBREAK, EVENT_ONCOMPILE_FAILURE, EVENT_ONCOMPILE_SUCCESS, EVENT_ONSTDOUT, EVENT_ONPROGRAM_EXIT, 
        SENDER_DEBUGGER, SENDER_HOST, SENDER_USER}