const OP_MOVE_ACTIVE_SESSION = 5;
const OP_LAUNCH_DEBUGGER = "DEBUGGER_LAUNCH";
const OP_CONNECTION = "CONNECTION";

const SENDER_HOST = "HOST_SERVER";
const SENDER_USER = "USER_SENDER";
const SENDER_DEBUGGER = "DEBUGGER_SENDER";

const ENV_REFRESH = 0;
const ENV_FAIL = 1;
const ENV_LAUNCHING = 2;
const ENV_SUCCESS = 3;
const ENV_MULTIPLE_ERROR = 4;

export {OP_CONNECTION, OP_LAUNCH_DEBUGGER, OP_MOVE_ACTIVE_SESSION,
        SENDER_DEBUGGER, SENDER_HOST, SENDER_USER,
        ENV_FAIL, ENV_LAUNCHING, ENV_MULTIPLE_ERROR, ENV_REFRESH, ENV_SUCCESS}